# Generated by Django 5.2.15 on 2026-06-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('guruh', models.CharField(max_length=50)),
                ('yosh', models.PositiveIntegerField()),
                ('faol', models.BooleanField(default=True)),
            ],
        ),
    ]
